search:
	g++ -fopenmp -std=c++17 -O2 -o essay-search ./*.cpp
	./essay-search data query.txt output.txt
search2:
	g++ -fopenmp -std=c++17 -O2 -o essay-search ./*.cpp
	./essay-search data-more query_more.txt output.txt
